name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.40.2

      - name: Lint
        run: pixi run lint

      - name: Run tests
        run: pixi run test
